name: flag_public_app
description: "Public App do Flag Platform - acompanhamento de campeonatos por atletas e torcedores."
version: 0.4.0
publish_to: none

environment:
  sdk: ^3.11.4

workspace:
  - packages/*

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.1
  flag_core: ^0.3.0
  flag_api: ^0.3.0
  flag_domain: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
